### ISSUE TITLE
How to crop to exact dimensions?

### ISSUE THREAD

**Issue by tsega** [CollectionFS/Meteor-cfs-graphicsmagick#8]
I have the following code to re-size images I upload

```JavaScript
gm(readStream, fileObj.name())
 .resize('90', '90')
 .crop('90', '90', 0, 0)
 .stream()
 .pipe(writeStream);
```
The images I get don't have the exact "90x90" pixels when shown on the browser. What could be the problem? How do I crop to exact dimensions?

**Comment by aldeed** [comment]
See the [resize docs](http://aheckmann.github.io/gm/docs.html). Pass "!" as third arg. `resize(90, 90, "!")`

And in your case you probably want to either crop or resize but not both.

**Comment by tsega** [comment]
Passing the string with the exclamation mark "!" a third argument to the `resize` method, **distorts the proportions of the image**.  See example below.

![image](https://cloud.githubusercontent.com/assets/206924/5742498/b47cbe7e-9c23-11e4-8dd0-67ab9279a394.png)


My thought was to resize it first with the proportions in place and crop out the leftover part of the picture. To have a similar thumbnail to the one next to this comment.

**Comment by aldeed** [comment]
OK, that makes sense.

**Comment by aldeed** [comment]
I think all the numbers have to be numbers, not strings, so that's probably the only issue.

**Comment by tsega** [comment]
@aldeed Thanks for the help, a more thorough googling pointed me to [an answer on SO](http://stackoverflow.com/questions/21591536/resize-and-crop-image-and-keeping-aspect-ratio-nodejs-gm). The principle being first resize to your desired with a `"^"` as a third parameter, to mean set either the height or width (it could also be both if the dimension fit) as a _minimum_ to the size specified. This insures that the other property will always have excess portions that you can crop to the exact size you need. The approach works perfectly!

**I just want to take this opportunity to thank you for the awesome work you're doing, your work is inspiring, thanks!**
